[0.000000] (-) TimerEvent: {}
[0.001581] (robot_shooter) JobQueued: {'identifier': 'robot_shooter', 'dependencies': OrderedDict()}
[0.002172] (robot_shooter) JobStarted: {'identifier': 'robot_shooter'}
[0.097519] (-) TimerEvent: {}
[0.198395] (-) TimerEvent: {}
[0.299295] (-) TimerEvent: {}
[0.400272] (-) TimerEvent: {}
[0.501137] (-) TimerEvent: {}
[0.602250] (-) TimerEvent: {}
[0.703135] (-) TimerEvent: {}
[0.803932] (-) TimerEvent: {}
[0.904685] (-) TimerEvent: {}
[1.005452] (-) TimerEvent: {}
[1.106257] (-) TimerEvent: {}
[1.207024] (-) TimerEvent: {}
[1.307792] (-) TimerEvent: {}
[1.408849] (-) TimerEvent: {}
[1.510067] (-) TimerEvent: {}
[1.610844] (-) TimerEvent: {}
[1.711475] (-) TimerEvent: {}
[1.812161] (-) TimerEvent: {}
[1.912968] (-) TimerEvent: {}
[2.013662] (-) TimerEvent: {}
[2.114292] (-) TimerEvent: {}
[2.214976] (-) TimerEvent: {}
[2.315734] (-) TimerEvent: {}
[2.416560] (-) TimerEvent: {}
[2.430314] (robot_shooter) StderrLine: {'line': b'Traceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/colcon_parallel_executor/executor/parallel.py", line 75, in execute\n    loop.run_until_complete(future)\n  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete\n    self.run_forever()\n  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever\n    self._run_once()\n  File "/usr/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once\n    event_list = self._selector.select(timeout)\n  File "/usr/lib/python3.10/selectors.py", line 469, in select\n    fd_event_list = self._selector.poll(timeout, max_ev)\nKeyboardInterrupt\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/colcon_core/executor/__init__.py", line 91, in __call__\n    rc = await self.task(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/colcon_core/task/__init__.py", line 93, in __call__\n    return await task_method(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/colcon_ros/task/ament_python/build.py", line 102, in build\n    return await extension.build(additional_hooks=additional_hooks)\n  File "/usr/lib/python3/dist-packages/colcon_core/task/python/build.py", line 96, in build\n    available_commands = await self._get_available_commands(\n  File "/usr/lib/python3/dist-packages/colcon_core/task/python/build.py", line 194, in _get_available_commands\n    output = await check_output(\n  File "/usr/lib/python3/dist-packages/colcon_core/subprocess.py", line 129, in check_output\n    assert not rc, f\'Expected {args} to pass: {stderr_data}\'\nAssertionError: Expected [\'/usr/bin/python3\', \'-W\', \'ignore:setup.py install is deprecated\', \'-W\', \'ignore:easy_install command is deprecated\', \'setup.py\', \'--help-commands\'] to pass: Traceback (most recent call last):\n  File "/root/ros2_ws/src/robot_shooter/setup.py", line 1, in <module>\n    from setuptools import find_packages, setup\n  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 16, in <module>\n    import setuptools.version\n  File "/usr/lib/python3/dist-packages/setuptools/version.py", line 1, in <module>\n    import pkg_resources\n  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 38, in <module>\n    import inspect\n  File "/usr/lib/python3.10/inspect.py", line 43, in <module>\n    import linecache\n  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load\n  File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked\n  File "<frozen importlib._bootstrap>", line 945, in _find_spec\n  File "<frozen importlib._bootstrap_external>", line 1439, in find_spec\n  File "<frozen importlib._bootstrap_external>", line 1411, in _get_spec\n  File "<frozen importlib._bootstrap_external>", line 1544, in find_spec\n  File "<frozen importlib._bootstrap_external>", line 147, in _path_stat\nKeyboardInterrupt\n\n'}
[2.445008] (robot_shooter) JobEnded: {'identifier': 'robot_shooter', 'rc': 'SIGINT'}
[2.457717] (-) EventReactorShutdown: {}
